ENH: ensure consistent formatting and intentation with TABS
It was a mix of spaces and tabs

- tabified all spaces
- added emacs and vim mode lines
- deleted trailing white spaces

Should have no effects on functioning

diff --git a/git-annex-remote-rclone b/git-annex-remote-rclone
--- a/git-annex-remote-rclone
+++ b/git-annex-remote-rclone
@@ -1,4 +1,7 @@
 #!/bin/bash
+# emacs: -*- mode: python; tab-width: 4; indent-tabs-mode: t -*-
+# ex: set sts=4 ts=4 sw=4 noet:
+#
 # git-annex-remote-rclone - wrapper to enable use of rclone-supported cloud providers as git-annex special remotes.
 #
 # Install in PATH as git-annex-remote-rclone
@@ -44,7 +47,7 @@ validate_layout() {
 			echo "INITREMOTE-FAILURE rclone_layout setting not recognized"
 			exit 1
 			;;
-	esac		
+	esac
 }
 
 # Sets LOC to the location to use to store a key.
@@ -60,7 +63,7 @@ calclocation () {
 			;;
 		nodir)
 			LOC="$REMOTE_TARGET:$REMOTE_PREFIX/"
-			;;	
+			;;
 		mixed)
 			ask DIRHASH "$1"
 			LOC="$REMOTE_TARGET:$REMOTE_PREFIX/$RET"
@@ -77,12 +80,12 @@ calclocation () {
 ask () {
 	echo "$1" "$2"
 	read -r resp
-    # Strip trailing carriage return, if present
-    resp="${resp%$'\r'}"
+	# Strip trailing carriage return, if present
+	resp="${resp%$'\r'}"
 	if echo "$resp" | grep '^VALUE '>/dev/null; then
-	    RET=$(echo "$resp" | cut -f2- -d' ')
-    	else
-	    RET=""
+		RET=$(echo "$resp" | cut -f2- -d' ')
+		else
+		RET=""
 	fi
 }
 
@@ -91,19 +94,19 @@ ask () {
 echo VERSION 1
 
 while read -r line; do
-    # Strip trailing carriage return, if present
-    line="${line%$'\r'}"
+	# Strip trailing carriage return, if present
+	line="${line%$'\r'}"
 	# shellcheck disable=SC2086
 	set -- $line
 	case "$1" in
 		INITREMOTE)
 			# Do anything necessary to create resources
 			# used by the remote. Try to be idempotent.
-			# 
+			#
 			# Use GETCONFIG to get any needed configuration
 			# settings, and SETCONFIG to set any persistent
 			# configuration settings.
-			# 
+			#
 			# (Note that this is not run every time, only when
 			# git annex initremote or git annex enableremote is
 			# run.)
@@ -111,31 +114,31 @@ while read -r line; do
 			getconfig prefix
 			REMOTE_PREFIX=$RET
 			if [ -z "$REMOTE_PREFIX" ]; then
-                		REMOTE_PREFIX="git-annex"
+				REMOTE_PREFIX="git-annex"
 			fi
 			if [ "$REMOTE_PREFIX" == "/" ]; then
-		                echo INITREMOTE-FAILURE "storing objects directly in the root (/) is not supported"
+				echo INITREMOTE-FAILURE "storing objects directly in the root (/) is not supported"
 			fi
 			setconfig prefix $REMOTE_PREFIX
 
 			getconfig target
 			REMOTE_TARGET=$RET
 			setconfig target "$REMOTE_TARGET"
-			
+
 			getconfig rclone_layout
 			RCLONE_LAYOUT=$RET
 			validate_layout
 			setconfig rclone_layout "$RCLONE_LAYOUT"
 
 			if [ -z "$REMOTE_TARGET" ]; then
-		                echo INITREMOTE-FAILURE "rclone remote target must be specified (use target= parameter)"
+				echo INITREMOTE-FAILURE "rclone remote target must be specified (use target= parameter)"
 			fi
 
-            if runcmd rclone mkdir "$REMOTE_TARGET:$REMOTE_PREFIX"; then
-                echo INITREMOTE-SUCCESS
-            else
-                echo INITREMOTE-FAILURE "Failed to create directory on remote. Ensure that 'rclone config' has been run."
-            fi
+			if runcmd rclone mkdir "$REMOTE_TARGET:$REMOTE_PREFIX"; then
+				echo INITREMOTE-SUCCESS
+			else
+				echo INITREMOTE-FAILURE "Failed to create directory on remote. Ensure that 'rclone config' has been run."
+			fi
 		;;
 		PREPARE)
 			# Use GETCONFIG to get configuration settings,
@@ -144,15 +147,15 @@ while read -r line; do
 
 			getconfig prefix
 			REMOTE_PREFIX="$RET"
-			
+
 			getconfig target
 			REMOTE_TARGET="$RET"
-			
+
 			getconfig rclone_layout
 			RCLONE_LAYOUT="$RET"
 			validate_layout
 
-            echo PREPARE-SUCCESS
+			echo PREPARE-SUCCESS
 		;;
 		TRANSFER)
 			op="$2"
@@ -167,13 +170,13 @@ while read -r line; do
 					calclocation "$key"
 					if [ ! -e "$file" ]; then
 						echo TRANSFER-FAILURE STORE "$key" "asked to store non-existent file $file"
-					else	
+					else
 						if runcmd rclone copy "$file" "$LOC"; then
 							echo TRANSFER-SUCCESS STORE "$key"
 						else
 							echo TRANSFER-FAILURE STORE "$key"
 						fi
-					fi					
+					fi
 				;;
 				RETRIEVE)
 					# Retrieve from a location based on
@@ -182,9 +185,9 @@ while read -r line; do
 					calclocation "$key"
 					# http://stackoverflow.com/questions/31396985/why-is-mktemp-on-os-x-broken-with-a-command-that-worked-on-linux
 					if GA_RC_TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/rclone-annex-tmp.XXXXXXXXX") &&
-					    runcmd rclone copy "$LOC$key" "$GA_RC_TEMP_DIR" &&
-					    mv "$GA_RC_TEMP_DIR/$key" "$file" &&
-					    rmdir "$GA_RC_TEMP_DIR"; then
+						runcmd rclone copy "$LOC$key" "$GA_RC_TEMP_DIR" &&
+						mv "$GA_RC_TEMP_DIR/$key" "$file" &&
+						rmdir "$GA_RC_TEMP_DIR"; then
 						echo TRANSFER-SUCCESS RETRIEVE "$key"
 					else
 						echo TRANSFER-FAILURE RETRIEVE "$key"
@@ -200,14 +203,14 @@ while read -r line; do
 			# Some rclone backends support multiple
 			# files under one name.
 			if check_result=$(rclone size "$LOC$key" 2>&1) &&
-			    echo "$check_result"|grep -E 'Total objects: [1-9][0-9]*\>' >&2 &&
-			    ! echo "$check_result"|grep 'Total size: 0 (0 bytes)' >&2; then
+				echo "$check_result"|grep -E 'Total objects: [1-9][0-9]*\>' >&2 &&
+				! echo "$check_result"|grep 'Total size: 0 (0 bytes)' >&2; then
 				echo CHECKPRESENT-SUCCESS "$key"
 			else
 				# rclone 1.29 used 'Total objects: 0'
 				# rclone 1.30 uses 'directory not found'
-				if echo "$check_result"|grep 'Total objects: 0' >&2 || 
-				   echo "$check_result"|grep ' directory not found' >&2; then 
+				if echo "$check_result"|grep 'Total objects: 0' >&2 ||
+				   echo "$check_result"|grep ' directory not found' >&2; then
 					echo CHECKPRESENT-FAILURE "$key"
 				else
 					# When the directory does not exist,
@@ -225,18 +228,18 @@ while read -r line; do
 			# Note that it's not a failure to remove a
 			# key that is not present.
 			if remove_result=$(rclone delete --retries 1 "$LOC$key" 2>&1); then
-		                echo REMOVE-SUCCESS "$key"
-	                else
-	    		   	# rclone 1.29 used Failed to purge: Couldn't find directory:
+				echo REMOVE-SUCCESS "$key"
+			else
+				# rclone 1.29 used Failed to purge: Couldn't find directory:
 				# rclone 1.30 used no such file or directory
 				# rclone 1.33 uses directory not found
-		                if echo "$remove_result" | grep " Failed to purge: Couldn't find directory: " >&2 ||
-				   echo "$remove_result" | grep ' no such file or directory' ||
-				   echo "$remove_result" | grep ' directory not found' >&2
-				then   
+				if echo "$remove_result" | grep " Failed to purge: Couldn't find directory: " >&2 ||
+					echo "$remove_result" | grep ' no such file or directory' ||
+					echo "$remove_result" | grep ' directory not found' >&2
+				then
 					echo REMOVE-SUCCESS "$key"
-		                else
-                		        echo REMOVE-FAILURE "$key"
+				else
+					echo REMOVE-FAILURE "$key"
 				fi
 			fi
 		;;
@@ -246,7 +249,7 @@ while read -r line; do
 			# to say that any other request is unsupported.
 			echo UNSUPPORTED-REQUEST
 		;;
-	esac	
+	esac
 done
 
 
