rclone 1.33 compatibility. Fixes #7 and #8.

diff --git a/git-annex-remote-rclone b/git-annex-remote-rclone
--- a/git-annex-remote-rclone
+++ b/git-annex-remote-rclone
@@ -207,13 +207,15 @@ while read line; do
 			calclocation "$key"
 			# Note that it's not a failure to remove a
 			# key that is not present.
-			if remove_result=$(rclone purge --retries 1 "$LOC$key" 2>&1); then
+			if remove_result=$(rclone delete --retries 1 "$LOC$key" 2>&1); then
 		                echo REMOVE-SUCCESS "$key"
 	                else
 	    		   	# rclone 1.29 used Failed to purge: Couldn't find directory:
-				# rclone 1.30 uses no such file or directory
+				# rclone 1.30 used no such file or directory
+				# rclone 1.33 uses directory not found
 		                if echo $remove_result | grep " Failed to purge: Couldn't find directory: " >&2 ||
-				   echo $remove_result | grep ' no such file or directory' >&2
+				   echo $remove_result | grep ' no such file or directory' ||
+				   echo $remove_result | grep ' directory not found' >&2
 				then   
 					echo REMOVE-SUCCESS "$key"
 		                else
