mark files as missing if their directory path doesn't exist

diff --git a/git-annex-remote-rclone b/git-annex-remote-rclone
--- a/git-annex-remote-rclone
+++ b/git-annex-remote-rclone
@@ -224,12 +224,15 @@ while read -r line; do
 					echo CHECKPRESENT-FAILURE "$key"
 				fi
 			else
-				# When the directory does not exist,
-				# the remote is not available.
-				# (A network remote would similarly
-				# fail with CHECKPRESENT-UNKNOWN
-				# if it couldn't be contacted).
-				echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-rclone failed to parse rclone output"
+                                res="$?"
+                                if [[ "$res" == "3" ]]; then
+                                  # directory doesn't exist
+                                  echo CHECKPRESENT-FAILURE "$key"
+                                else
+                                  # some other error occured (e.g. a network error)
+                                  echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-rclone failed to parse rclone output"
+                                fi
+
 			fi
 		;;
 		REMOVE)
